### ISSUE TITLE
Tests no funcionan con Python 3

### ISSUE THREAD

**Issue by edvm** [nicoechaniz/IPP#1]
Al correr los tests se obtiene el siguiente traceback:
`File "<frozen importlib._bootstrap_external>", line 662, in exec_module
        File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
        File "/home/edvm/repos/ipp/ipp/relevamiento/urls.py", line 26, in <module>
          from views import *
      ImportError: No module named 'views'`

**Comment by edvm** [comment]
Fixed at: https://github.com/nicoechaniz/IPP/pull/2

**Comment by edvm** [comment]
```
 Traceback (most recent call last):
    File "/home/edvm/.virtualenvs/ipp/lib/python3.5/site-packages/behave/model.py", line 1456, in run
      match.run(runner.context)
    File "/home/edvm/.virtualenvs/ipp/lib/python3.5/site-packages/behave/model.py", line 1903, in run
      self.func(context, *args, **kwargs)
    File "bdd/features/steps/crear_muestra.py", line 55, in impl
      ocurrencias = context.browser.find_by_text(unicode(muestra))
  NameError: name 'unicode' is not defined
```

**Comment by nicoechaniz** [comment]
emiliano esto quedó fixeado, no?
lo cierro

**Comment by mgaitan** [comment]
no he tenido tiempo de ponerme a chusmear bien, pero si es que están pasado, evidentemente el coverage de los tests no debe alcanzar porque hay muchos casts explicitos a "unicode" que no son necesarios (y son incompatibles) en py3. 

voy a tratar de mandar un parche más tarde, también voto por pasarlo a py3, pero no invertir tiempo en hacerlo compatible con py2. qué dicen?

**Comment by edvm** [comment]
@nicoechaniz Corren los tests, si, cierro este issue. @mgaitan dice que hay varios lugares donde hay codigo no python3 friendly, que no saltan porque no son tocado por los tests, +1 a migrar el código a py3 (sin poner esfuerzo en tener compat para py2)!
En caso que se decida pasar a py3 (quien decide esto? :)), por favor crear un nuevo issue con esa tarea. Cierro este issue.

**Comment by nicoechaniz** [comment]
@mgaitan done.
